### ISSUE TITLE
Crashes on inserting certain crops into virtual farm?

### ISSUE THREAD

**Issue by Seegras** [Arcaratus/VirtualMachines#3]
I think I shift-clicked cactus into the virtual farm, with minecraft immediately crashing:

java.lang.NullPointerException: Ticking block entity
	at com.arcaratus.virtualmachines.virtual.VirtualFarm$DefaultPlantHandler.requiresDirt(VirtualFarm.java:235)
	at com.arcaratus.virtualmachines.block.machine.TileFarm.canStart(TileFarm.java:159)
	at com.arcaratus.virtualmachines.block.machine.TileVirtualMachine.func_73660_a(TileVirtualMachine.java:212)
	at com.arcaratus.virtualmachines.block.machine.TileFarm.func_73660_a(TileFarm.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1832)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Thread.java:748)

**Comment by Seegras** [comment]
Actually, it was carrots. !?

**Comment by Arcaratus** [comment]
I will take a look into this... Does this happen when you don't shift click the crops in?

**Comment by Arcaratus** [comment]
What version are you using?

**Comment by Arcaratus** [comment]
Cannot reproduce.
