### ISSUE TITLE
Reoccurring ArrayIndexOutOfBoundsException when inserted seeds to Virtual Farm via Refined storage exporter

### ISSUE THREAD

**Issue by Aphyxia** [Arcaratus/VirtualMachines#4]
Player inserted melon seeds to virtual farm via Refined storage exporter.
Resulted in : 
`java.lang.ArrayIndexOutOfBoundsException: 32
    at cofh.thermalexpansion.block.TileReconfigurable.func_180462_a(TileReconfigurable.java:351)
    at net.minecraftforge.items.wrapper.SidedInvWrapper.insertItem(SidedInvWrapper.java:143)
    at net.minecraftforge.items.ItemHandlerHelper.insertItem(ItemHandlerHelper.java:45)
    at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeExporter.doExport(NetworkNodeExporter.java:171)
    at com.raoulvdberge.refinedstorage.apiimpl.network.node.NetworkNodeExporter.update(NetworkNodeExporter.java:74)
    at com.raoulvdberge.refinedstorage.apiimpl.network.NetworkNodeListener.onWorldTick(NetworkNodeListener.java:23)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1281_NetworkNodeListener_onWorldTick_WorldTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:179)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPostWorldTick(FMLCommonHandler.java:273)
    at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:774)
    at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396)
    at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
    at java.lang.Thread.run(Unknown Source)`
Pastebin for full crashlog: https://pastebin.com/RdtDnXHg

I haven't tried replicating it. All I know is what the player told me.

**Comment by Arcaratus** [comment]
Cannot reproduce.
