### ISSUE TITLE
crash report for VirtualMachines-1.12.2-1.0.0.3.jar 

### ISSUE THREAD

**Issue by WilliamBlaze** [Arcaratus/VirtualMachines#5]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 3/20/18 10:15 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Virtual Machines (virtualmachines)
Caused by: java.lang.NoClassDefFoundError: com/arcaratus/virtualmachines/VirtualMachines$1
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:516)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:568)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:231)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.arcaratus.virtualmachines.VirtualMachines$1
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 38 more
Caused by: java.lang.NoClassDefFoundError: cofh/core/gui/CreativeTabCore
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 40 more
Caused by: java.lang.ClassNotFoundException: cofh.core.gui.CreativeTabCore
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 44 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3754245944 bytes (3580 MB) / 4225236992 bytes (4029 MB) up to 4225236992 bytes (4029 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2629 Optifine OptiFine_1.12.2_HD_U_C9 52 mods loaded, 52 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version               | Source                                        | Signature                                |
	|:----- |:------------------- |:--------------------- |:--------------------------------------------- |:---------------------------------------- |
	| UC    | minecraft           | 1.12.2                | minecraft.jar                                 | None                                     |
	| UC    | mcp                 | 9.42                  | minecraft.jar                                 | None                                     |
	| UC    | FML                 | 8.0.99.99             | forge-1.12.2-14.23.2.2629.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | forge               | 14.23.2.2629          | forge-1.12.2-14.23.2.2629.jar                 | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UC    | foamfixcore         | 7.7.4                 | minecraft.jar                                 | None                                     |
	| UC    | mercurius_updater   | 1.0                   | MercuriusUpdater-1.12.2.jar                   | None                                     |
	| UC    | mobscrops           | 2.1.0                 | [MC1.12.2]mobscrops-2.1.0.jar                 | None                                     |
	| UC    | autoplanter         | 1.3                   | AutoPlanter-1.3.jar                           | None                                     |
	| UC    | baubles             | 1.5.2                 | Baubles-1.12-1.5.2.jar                        | None                                     |
	| UC    | biomesoplenty       | 7.0.1.2334            | BiomesOPlenty-1.12.2-7.0.1.2334-universal.jar | None                                     |
	| UC    | ctm                 | MC1.12-0.2.3.12       | CTM-MC1.12-0.2.3.12.jar                       | None                                     |
	| UC    | chisel              | MC1.12.2-0.2.0.31     | Chisel-MC1.12.2-0.2.0.31.jar                  | None                                     |
	| UC    | extendedrenderer    | v1.0                  | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UC    | coroutil            | 1.12.1-1.1.24         | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UC    | configmod           | v1.0                  | coroutil-1.12.1-1.1.24.jar                    | None                                     |
	| UC    | customnpcs          | 1.12                  | CustomNPCs_1.12.2(20jan18).jar                | None                                     |
	| UC    | customstartinggear  | 1.2.0                 | CustomStartingGear-1.12-1.2.0.9-universal.jar | None                                     |
	| UC    | elevatorid          | 1.3.6                 | ElevatorMod-1.12.2-1.3.6.jar                  | None                                     |
	| UC    | extrautils2         | 1.0                   | extrautils2-1.12-1.7.5.jar                    | None                                     |
	| UC    | foamfix             | 0.9.4-1.12.2          | FoamFix-1.12.2-0.9.4-Anarchy.jar              | None                                     |
	| UC    | grapplemod          | 1.12-v10              | grapplemod-1.12-v10.jar                       | None                                     |
	| UC    | jei                 | 4.8.5.159             | jei_1.12.2-4.8.5.159.jar                      | None                                     |
	| UC    | journeymap          | 1.12.2-5.5.2          | journeymap-1.12.2-5.5.2.jar                   | None                                     |
	| UC    | keepinginventory    | 2.4                   | KeepingInventory-1.12.2-2.4.jar               | None                                     |
	| UC    | malisiscore         | 1.12.2-6.4.0          | malisiscore-1.12.2-6.4.0.jar                  | None                                     |
	| UC    | malisisblocks       | 1.12.2-6.1.0          | malisisblocks-1.12.2-6.1.0.jar                | None                                     |
	| UC    | malisisdoors        | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                 | None                                     |
	| UC    | malisisswitches     | 1.12.2-5.1.0          | malisisswitches-1.12.2-5.1.0.jar              | None                                     |
	| UC    | radixcore           | 1.12.x-2.2.1          | RadixCore-1.12.x-2.2.1-universal.jar          | None                                     |
	| UC    | mca                 | 1.12.2-5.3.1          | MCA-1.12.x-5.3.1-universal.jar                | None                                     |
	| UC    | naturescompass      | 1.5.1                 | NaturesCompass-1.12.2-1.5.1.jar               | None                                     |
	| UC    | openglider          | @VERSION@             | OpenGlider-1.12.1-1.1.0.jar                   | None                                     |
	| UC    | thutcore            | 5.16.2                | pokecube_aio_1.12.2-1.0.0d.jar                | None                                     |
	| UC    | pceditmod           | 1.10.2-2.0.0          | pokecube-core-1.12.2-6.36.7.jar               | None                                     |
	| UC    | pokecube            | 6.36.7                | pokecube-core-1.12.2-6.36.7.jar               | None                                     |
	| UC    | pokecube_ml         | 0.1.0                 | pokecube-core-1.12.2-6.36.7.jar               | None                                     |
	| UC    | thut_wearables      | 3.1.6                 | thut-wearables-1.12.2-3.1.6.jar               | None                                     |
	| UC    | thut_bling          | 2.0.3                 | thut_bling-1.12.2-2.0.3.jar                   | None                                     |
	| UC    | pokecube_adventures | 6.14.15               | pokecube-revival-1.12.2-6.14.15.jar           | None                                     |
	| UC    | pokecube_mobs       | 4.7.0                 | pokecube-mobs-1.12.2-4.7.0.jar                | None                                     |
	| UC    | pokecube_moves      | 4.7.0                 | pokecube-mobs-1.12.2-4.7.0.jar                | None                                     |
	| UC    | pokecube_origin     | 4.7.0                 | pokecube-mobs-1.12.2-4.7.0.jar                | None                                     |
	| UC    | pokecube_compat     | 1.0                   | pokecube-revival-1.12.2-6.14.15.jar           | None                                     |
	| UC    | thutcore_compat     | 1.0                   | pokecube_aio_1.12.2-1.0.0d.jar                | None                                     |
	| UC    | pokeplayer          | 1.12.2-1.0.1          | pokeplayer-1.12.2-1.0.1.jar                   | None                                     |
	| UC    | projecte            | 1.12-PE1.0.0          | ProjectE-1.12-PE1.2.0.jar                     | None                                     |
	| UC    | reap                | 1.5.1                 | reap-1.5.1.jar                                | None                                     |
	| UC    | redstoneflux        | 2.0.1                 | RedstoneFlux-1.12-2.0.1.2-universal.jar       | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UC    | ropebridge          | 2.0.5                 | ropebridge-1.12-2.0.7.jar                     | None                                     |
	| UC    | upsizer             | 4.0.1                 | upsizer-mc1.12-4.0.1.jar                      | None                                     |
	| UE    | virtualmachines     | 1.12.2-1.0.0.2-CUSTOM | VirtualMachines-1.12.2-1.0.0.3.jar            | None                                     |
	| UC    | weather2            | 1.12.1-2.5.8          | weather2-1.12.1-2.5.8.jar                     | None                                     |

	Loaded coremods (and transformers): 
MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
  
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  
Born in a Barn (Born+In+A+Barn+V1.8-1.12-1.0.jar)
  com.chocohead.biab.BornInABarn
Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (FoamFix-1.12.2-0.9.4-Anarchy.jar)
  pl.asie.foamfix.coremod.FoamFixTransformer
	GL info: ' Vendor: 'Intel' Version: '3.1.0 - Build 9.17.10.4459' Renderer: 'Intel(R) HD Graphics 2000'
	OptiFine Version: OptiFine_1.12.2_HD_U_C9
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.1.0 - Build 9.17.10.4459
	OpenGlRenderer: Intel(R) HD Graphics 2000
	OpenGlVendor: Intel
	CpuCount: 8

**Comment by Arcaratus** [comment]
Do you have CoFH Core, Thermal Foundation and Thermal Expansion installed?

**Comment by WilliamBlaze** [comment]
reinstalled a fresh download of CoFH, Thermal foundation, Thermal expansion and then the issue has been corrected.
