### ISSUE TITLE
Incompatible with latest CoFH

### ISSUE THREAD

**Issue by Xiaminou** [Arcaratus/VirtualMachines#7]
[crash-2018-04-07_13.46.08-client.txt](https://github.com/Arcaratus/VirtualMachines/files/1886321/crash-2018-04-07_13.46.08-client.txt)

**Comment by CobaltRealm** [comment]
Same crash error :/

https://pastebin.com/JQhYgR1H

**Comment by JasonKillsUs** [comment]
same here :-(

**Comment by hron84** [comment]
Same:

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  FMLPlugin (elulib-0.1.12.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  ItemPatchingLoader (ItemPhysic_Full 1.4.11_mc1.12.2.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 4/18/18 7:18 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Virtual Machines (virtualmachines)
Caused by: java.lang.NoClassDefFoundError: com/arcaratus/virtualmachines/plugins/PluginActuallyAdditions
	at com.arcaratus.virtualmachines.init.VMPlugins.preInit(VMPlugins.java:20)
	at com.arcaratus.virtualmachines.proxy.CommonProxy.preInit(CommonProxy.java:14)
	at com.arcaratus.virtualmachines.proxy.ClientProxy.preInit(ClientProxy.java:16)
	at com.arcaratus.virtualmachines.VirtualMachines.preInit(VirtualMachines.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:600)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:278)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:256)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:602)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:270)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: com.arcaratus.virtualmachines.plugins.PluginActuallyAdditions
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 44 more
Caused by: java.lang.NoClassDefFoundError: cofh/core/util/ModPlugin
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 46 more
Caused by: java.lang.ClassNotFoundException: cofh.core.util.ModPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 50 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 952615280 bytes (908 MB) / 1636827136 bytes (1561 MB) up to 2863661056 bytes (2731 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx3072m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.2.2653 84 mods loaded, 84 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                       | Version                  | Source                                          | Signature                                |
	|:----- |:------------------------ |:------------------------ |:----------------------------------------------- |:---------------------------------------- |
	| UCH   | minecraft                | 1.12.2                   | minecraft.jar                                   | None                                     |
	| UCH   | mcp                      | 9.42                     | minecraft.jar                                   | None                                     |
	| UCH   | FML                      | 8.0.99.99                | forge-1.12.2-14.23.2.2653.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | forge                    | 14.23.2.2653             | forge-1.12.2-14.23.2.2653.jar                   | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCH   | creativecoredummy        | 1.0.0                    | minecraft.jar                                   | None                                     |
	| UCH   | itemphysic               | 1.4.0                    | minecraft.jar                                   | None                                     |
	| UCH   | ivtoolkit                | 1.3.3-1.12               | minecraft.jar                                   | None                                     |
	| UCH   | elucore                  | 1.0                      | minecraft.jar                                   | None                                     |
	| UCH   | movillages               | 1.5.4                    | [1.12]MoVillages-1.5.4.jar                      | None                                     |
	| UCH   | jei                      | 4.8.5.159                | jei_1.12.2-4.8.5.159.jar                        | None                                     |
	| UCH   | abyssalcraft             | 1.9.4.7                  | AbyssalCraft-1.12.2-1.9.4.7.jar                 | 220f10d3a93b3ff5fbaa7434cc629d863d6751b9 |
	| UCH   | codechickenlib           | 3.1.6.339                | CodeChickenLib-1.12.2-3.1.6.339-universal.jar   | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCH   | ancientwarfare           | @VERSION@                | ancientwarfare-1.12.2-2.5.119.jar               | None                                     |
	| UCH   | redstoneflux             | 2.0.1                    | RedstoneFlux-1.12-2.0.1.2-universal.jar         | d4f1503fbacd9b9fb767720420c5395104239ec9 |
	| UCH   | ancientwarfareautomation | @VERSION@                | ancientwarfare-1.12.2-2.5.119.jar               | None                                     |
	| UCH   | ancientwarfarenpc        | @VERSION@                | ancientwarfare-1.12.2-2.5.119.jar               | None                                     |
	| UCH   | ancientwarfarestructure  | @VERSION@                | ancientwarfare-1.12.2-2.5.119.jar               | None                                     |
	| UCH   | baubles                  | 1.5.2                    | Baubles-1.12-1.5.2.jar                          | None                                     |
	| UCH   | botania                  | r1.10-353                | Botania r1.10-353.jar                           | None                                     |
	| UCH   | craftstudioapi           | 1.0.0                    | CraftStudio-1.0.0.93-mc1.12-alpha.jar           | None                                     |
	| UCH   | animania                 | 1.4.7                    | animania-1.12.2-1.4.7.jar                       | None                                     |
	| UCH   | applecore                | 3.1.1                    | AppleCore-mc1.12.2-3.1.1.jar                    | None                                     |
	| UCH   | astralsorcery            | 1.8.5                    | astralsorcery-1.12.2-1.8.5.jar                  | None                                     |
	| UCH   | birdsnests               | 2.1.0                    | BirdsNests1.12.2-2.1.0.jar                      | None                                     |
	| UCH   | blockcraftery            | 0.1.3                    | blockcraftery-0.1.3.jar                         | None                                     |
	| UCH   | guideapi                 | 1.12-2.1.5-60            | Guide-API-1.12-2.1.5-60.jar                     | None                                     |
	| UCH   | bloodmagic               | 1.12.2-2.2.8-91          | BloodMagic-1.12.2-2.2.8-91.jar                  | None                                     |
	| UCH   | bonsaitrees              | 1.0.3                    | bonsaitrees-1.0.3-b67.jar                       | None                                     |
	| UCH   | carryon                  | 1.8                      | CarryOn MC1.12.2 v1.8.jar                       | None                                     |
	| UCH   | ceramics                 | 1.12-1.3.4               | Ceramics-1.12-1.3.4.jar                         | None                                     |
	| UCH   | chameleon                | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                        | None                                     |
	| UCH   | ctm                      | MC1.12-0.2.3.12          | CTM-MC1.12-0.2.3.12.jar                         | None                                     |
	| UCH   | chisel                   | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                    | None                                     |
	| UCH   | chunkpregenerator        | 1.7                      | Chunk Pregenerator V1.12-1.7.1.jar              | None                                     |
	| UCH   | cofhcore                 | 4.3.11                   | CoFHCore-1.12.2-4.3.11.6-universal.jar          | None                                     |
	| UCH   | cofhworld                | 1.1.1                    | CoFHWorld-1.12.2-1.1.1.12-universal.jar         | None                                     |
	| UCH   | cookingforblockheads     | 6.3.26                   | CookingForBlockheads_1.12.2-6.3.26.jar          | None                                     |
	| UCH   | creativecore             | 1.9.9                    | CreativeCore_v1.9.22_mc1.12.2.jar               | None                                     |
	| UCH   | creeperconfetti          | 1.4.2                    | creeperconfetti-1.4.2.jar                       | None                                     |
	| UCH   | cyclopscore              | 0.11.5                   | CyclopsCore-1.12.2-0.11.5.jar                   | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | dailies                  | 1.12.2-6                 | dailies-1.12.2-6.jar                            | None                                     |
	| UCH   | dsurround                | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
	| UCH   | presets                  | 3.4.7.2                  | DynamicSurroundings-1.12.2-3.4.7.2.jar          | None                                     |
	| UCH   | embers                   | 0.230                    | embers-0.230.jar                                | None                                     |
	| UCH   | everlastingabilities     | 1.3.15                   | EverlastingAbilities-1.12.2-1.3.15.jar          | bd0353b3e8a2810d60dd584e256e364bc3bedd44 |
	| UCH   | extraalchemy             | 0.3.8.4-release          | extraalchemy-0.3.8.4-release.jar                | None                                     |
	| UCH   | ftblib                   | 5.0.2.10                 | FTBLib-5.0.2.10.jar                             | None                                     |
	| UCH   | ftbutilities             | 5.0.2.10                 | FTBUtilities-5.0.2.10.jar                       | None                                     |
	| UCH   | inventorypets            | 1.4.9.9b                 | inventorypets-1.12-1.4.9.9b.jar                 | None                                     |
	| UCH   | inventorytweaks          | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                        | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCH   | ironbackpacks            | 1.12.2-3.0.5-6           | IronBackpacks-1.12.2-3.0.5-6.jar                | None                                     |
	| UCH   | journeymap               | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                     | None                                     |
	| UCH   | minecolonies             | 1.12.2-0.8.7582          | minecolonies-universal-1.12.2-0.8.7582.jar      | None                                     |
	| UCH   | modnametooltip           | 1.10.0                   | modnametooltip_1.12.2-1.10.0.jar                | None                                     |
	| UCH   | mousetweaks              | 2.8                      | MouseTweaks-2.8-mc1.12.1.jar                    | None                                     |
	| UCH   | harvestcraft             | 1.12.2t                  | Pam's HarvestCraft 1.12.2t.jar                  | None                                     |
	| UCH   | placebo                  | 1.3.2                    | Placebo-1.12.2-1.3.2.jar                        | None                                     |
	| UCH   | plants2                  | 2.8.2                    | Plants-1.12.2-2.8.2.jar                         | None                                     |
	| UCH   | reccomplex               | 1.4.7                    | RecurrentComplex-1.4.7.jar                      | None                                     |
	| UCH   | recycler                 | 1.5.0                    | recycler-1.5.0-1.12.jar                         | None                                     |
	| UCH   | roguelike                | 1.8.0                    | RoguelikeDungeons-1.12.2-1.8.0.jar              | None                                     |
	| UCH   | roots                    | 0.104                    | roots-2-0.104.jar                               | None                                     |
	| UCH   | rustic                   | 1.0.3                    | rustic-1.0.3.jar                                | None                                     |
	| UCH   | shetiphiancore           | 3.5.6                    | shetiphiancore-1.12.0-3.5.6.jar                 | None                                     |
	| UCH   | solcarrot                | 1.2.0                    | solcarrot-1.12.1-1.2.0.jar                      | None                                     |
	| UCH   | storagedrawers           | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.6.jar                 | None                                     |
	| UCH   | terraqueous              | 1.4.11                   | terraqueous-1.12.0-1.4.11.jar                   | None                                     |
	| UCH   | thebetweenlands          | 3.3.7                    | TheBetweenlands-3.3.7-universal.jar             | 38067d6878811efb38b6a045521cfd80b9b60b38 |
	| UCH   | theoneprobe              | 1.4.22                   | theoneprobe-1.12-1.4.22.jar                     | None                                     |
	| UCH   | thermalfoundation        | 2.3.11                   | ThermalFoundation-1.12.2-2.3.11.9-universal.jar | None                                     |
	| UCH   | thermalexpansion         | 5.3.11                   | ThermalExpansion-1.12.2-5.3.12.17-universal.jar | None                                     |
	| UCH   | tp                       | 3.2.25                   | tinyprogressions-1.12.2-3.3.25-Release.jar      | None                                     |
	| UCH   | tombstone                | 2.8.7                    | tombstone-2.8.7-1.12.jar                        | None                                     |
	| UCH   | toroquest                | 1.12.2-5.2               | toroquest-1.12.2-5.2.jar                        | None                                     |
	| UCH   | totemic                  | 1.12.2-0.10.3            | Totemic-1.12.2-0.10.3.jar                       | 21d11d7bf4d97b465382a1f95428029aac6daaea |
	| UCH   | twilightforest           | 3.6.345                  | twilightforest-1.12.2-3.6.345-universal.jar     | None                                     |
	| UCH   | veining                  | 1.3.0                    | veining-1.3.0-1.12.x.jar                        | None                                     |
	| UCH   | vc                       | 5.6.1                    | ViesCraft-1.12.2-5.6.1.jar                      | None                                     |
	| UCH   | villagenames             | 2.0                      | VillageNames-1.12.2-2.0.jar                     | None                                     |
	| UCE   | virtualmachines          | 1.12.2-1.0.0.2-CUSTOM    | VirtualMachines-1.12.2-1.0.0.3.jar              | None                                     |
	| UCH   | wanionlib                | 1.12.2-1.5               | WanionLib-1.12.2-1.5.jar                        | None                                     |
	| UCH   | waystones                | 4.0.33                   | Waystones_1.12.2-4.0.33.jar                     | None                                     |
	| UCH   | elulib                   | 0.1.12                   | elulib-0.1.12.jar                               | None                                     |
	| UCH   | unidict                  | 1.12.2-2.4c              | UniDict-1.12.2-2.4c.jar                         | None                                     |

	Loaded coremods (and transformers): 
CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  team.chisel.ctm.client.asm.CTMTransformer
ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  shetiphian.asm.ClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
FMLPlugin (elulib-0.1.12.jar)
  elucent.elulib.asm.ASMTransformer
TheBetweenlandsLoadingPlugin (TheBetweenlands-3.3.7-core.jar)
  thebetweenlands.core.TheBetweenlandsClassTransformer
ItemPatchingLoader (ItemPhysic_Full 1.4.11_mc1.12.2.jar)
  com.creativemd.itemphysic.ItemTransformer
AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  
AppleCore (AppleCore-mc1.12.2-3.1.1.jar)
  squeek.applecore.asm.TransformerModuleHandler
IvToolkit (IvToolkit-1.3.3-1.12.jar)
  
DynamicSurroundingsCore (DynamicSurroundings-1.12.2-3.4.7.2.jar)
  org.blockartistry.DynSurround.asm.Transformer
CreativePatchingLoader (CreativeCore_v1.9.22_mc1.12.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 388.13' Renderer: 'GeForce GTX 750 Ti/PCIe/SSE2'
```

Anyone could find proper versions?

**Comment by Arcaratus** [comment]
There is a new version out now where this is fixed.
